AWSTemplateFormatVersion: 2010-09-09
Description: >-
  IAM role for serviceaccount "kube-system/aws-node" [created and managed by
  eksctl]
Resources:
  Role1:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'oidc.eks.us-east-1.amazonaws.com/id/1D0EDA1665A6CCAA78249DBA68D926A6:aud': sts.amazonaws.com
                'oidc.eks.us-east-1.amazonaws.com/id/1D0EDA1665A6CCAA78249DBA68D926A6:sub': 'system:serviceaccount:kube-system:aws-node'
                #'oidc.eks.us-east-1.amazonaws.com/id/E2887E712D99522A376BA25C168ACCA3:aud': sts.amazonaws.com
                #'oidc.eks.us-east-1.amazonaws.com/id/E2887E712D99522A376BA25C168ACCA3:sub': 'system:serviceaccount:kube-system:aws-node'

            Effect: Allow
            Principal:
              Federated: >-
                arn:aws:iam::291045144839:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/E2887E712D99522A376BA25C168ACCA3
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
Outputs:
  Role1:
    Value: !GetAtt Role1.Arn
